### ISSUE TITLE
Title label for each week

### ISSUE THREAD

**Issue by HasanAbdullah31** [hunter-college-ossd-spr19/Shane-Lester99-weekly#1]
This isn't really an "issue" as it is a suggestion/personal preference thing. Maybe use 3 #'s instead of 2 in your labels? That way "Week _" is like an h2 size and the title is an h3 size. (e.g. for week 1 post, do
"### Defining Open Source. What Exactly Is It?" instead of "## Defining Open Source. What Exactly Is It?")

**Comment by Shane-Lester99** [comment]
I agree, thanks for the advice! I switched it
