### ISSUE TITLE
Awkward rendering of bullet points in week 2 post

### ISSUE THREAD

**Issue by codesue** [hunter-college-ossd-spr19/Shane-Lester99-weekly#2]
The bullet points section of [week 2's post](https://github.com/hunter-college-ossd-spr19/Shane-Lester99-weekly/blob/gh-pages/_posts/2019-02-08-week02.md) is being rendered as a code block because of how it is indented in the post's markdown file. It looks good with GitHub's default theme:
<img width="886" alt="screen shot 2019-02-18 at 9 27 03 pm" src="https://user-images.githubusercontent.com/11793274/52986486-bfbe3b80-33c5-11e9-822a-ab393a7b25d1.png">
But it looks awkward with the blog's site theme:
<img width="754" alt="screen shot 2019-02-18 at 9 27 35 pm" src="https://user-images.githubusercontent.com/11793274/52986196-edef4b80-33c4-11e9-8f06-080025b264a4.png">

**Comment by Shane-Lester99** [comment]
Hey thanks for letting me know! What would be the markdown syntax to fix this?

**Comment by codesue** [comment]
You're using the correct syntax. Un-indenting will fix the error.

**Comment by Shane-Lester99** [comment]
Thanks for clarifying! Done!
