### ISSUE TITLE
Week 3 Post Correction to Last Sentence

### ISSUE THREAD

**Issue by stewartweiss** [hunter-college-ossd-spr19/Shane-Lester99-weekly#3]
In [the post  for week 3](https://github.com/hunter-college-ossd-spr19/Shane-Lester99-weekly/blob/gh-pages/_posts/2019-02-15-week03.md), the very last line has the title repeated again. I suspect this is not intentional.

**Comment by Shane-Lester99** [comment]
Thanks! Taken care of!
